import type { MatchDetails } from '@/routes/(dashboard)/-components/agent-preview-card'

export const clientPreviewMatches: MatchDetails[] = [
	{
		id: 'preview-1',
		name: 'Alex Morgan',
		role: 'agent',
		location: 'Austin, TX',
		zipCodes: ['78704', '78745'],
		fitScore: 97,
		status: 'new',
		date: 'Today',
		experience: '12 years',
		agency: 'PRE Partner Realty',
		specialties: ['First-time buyers', 'Fast timelines', 'Negotiation'],
		about: 'Calm, responsive agent focused on clear expectations.',
		scores: {
			'Working Style': 4.9,
			Communication: 4.8,
			Transparency: 4.9,
			Fit: 5,
		},
	},
	{
		id: 'preview-2',
		name: 'Jordan Lee',
		role: 'agent',
		location: 'Austin, TX',
		zipCodes: ['78701', '78703'],
		fitScore: 94,
		status: 'new',
		date: 'Today',
		experience: '9 years',
		agency: 'Urban Nest Realty',
		specialties: ['Condos', 'Relocation', 'Offer strategy'],
		about: 'Data-driven agent with a direct communication style.',
		scores: {
			'Working Style': 4.7,
			Communication: 4.9,
			Transparency: 4.7,
			Fit: 4.8,
		},
	},
	{
		id: 'preview-3',
		name: 'Sam Rivera',
		role: 'agent',
		location: 'Austin, TX',
		zipCodes: ['78731', '78757'],
		fitScore: 91,
		status: 'new',
		date: 'Today',
		experience: '15 years',
		agency: 'Local Key Realty',
		specialties: ['Move-up buyers', 'Listings', 'Pricing'],
		about: 'Experienced local advisor with strong pricing instincts.',
		scores: {
			'Working Style': 4.6,
			Communication: 4.6,
			Transparency: 4.8,
			Fit: 4.7,
		},
	},
]

export const agentPreviewMatches: MatchDetails[] = [
	{
		id: 'preview-client-1',
		name: 'Alex Morgan',
		role: 'agent',
		location: 'Austin, TX',
		zipCodes: ['78704', '78745'],
		fitScore: 97,
		status: 'new',
		date: 'Today',
		experience: 'Ready now',
		agency: 'Buyer profile',
		specialties: ['First-time buyer', 'Fast timeline', 'Clear communication'],
		about: 'Preview of the matched client cards agents will see.',
		scores: {
			'Working Style': 4.9,
			Communication: 4.8,
			Transparency: 4.9,
			Fit: 5,
		},
	},
	{
		id: 'preview-client-2',
		name: 'Jordan Lee',
		role: 'agent',
		location: 'Austin, TX',
		zipCodes: ['78701', '78703'],
		fitScore: 94,
		status: 'new',
		date: 'Today',
		experience: 'Exploring',
		agency: 'Seller profile',
		specialties: ['Listing prep', 'Pricing strategy', 'Transparency'],
		about: 'Preview of the matched client cards agents will see.',
		scores: {
			'Working Style': 4.7,
			Communication: 4.9,
			Transparency: 4.7,
			Fit: 4.8,
		},
	},
	{
		id: 'preview-client-3',
		name: 'Sam Rivera',
		role: 'agent',
		location: 'Austin, TX',
		zipCodes: ['78731', '78757'],
		fitScore: 91,
		status: 'new',
		date: 'Today',
		experience: '3 months',
		agency: 'Buyer profile',
		specialties: ['Move-up buyer', 'Negotiation', 'Local expertise'],
		about: 'Preview of the matched client cards agents will see.',
		scores: {
			'Working Style': 4.6,
			Communication: 4.6,
			Transparency: 4.8,
			Fit: 4.7,
		},
	},
]
