[build]
builder = "RAILPACK"
buildCommand = "vp run build"

[deploy]
preDeployCommand = "vp run db:migrate && vp run db:init"
runtime = "V2"
numReplicas = 1
startCommand = "vp run start"
healthcheckPath = "/"
useLegacyStacker = false
ipv6EgressEnabled = false
restartPolicyType = "ALWAYS"
healthcheckTimeout = 300
