[build]
builder = "RAILPACK"
buildCommand = "vp build"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "vp run db:migrate && vp run db:init && vp run start"
healthcheckPath = "/"
sleepApplication = true
useLegacyStacker = false
ipv6EgressEnabled = false
restartPolicyType = "ALWAYS"
healthcheckTimeout = 300
