import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync, realpathSync, writeFileSync } from 'node:fs'
import { basename } from 'node:path'

const MASK_64 = (1n << 64n) - 1n

function rotateLeft(value: bigint, bits: bigint): bigint {
	return ((value << bits) | (value >> (64n - bits))) & MASK_64
}

type SipState = [bigint, bigint, bigint, bigint]

function sipRound(state: SipState): void {
	state[0] = (state[0] + state[1]) & MASK_64
	state[1] = rotateLeft(state[1], 13n) ^ state[0]
	state[0] = rotateLeft(state[0], 32n)
	state[2] = (state[2] + state[3]) & MASK_64
	state[3] = rotateLeft(state[3], 16n) ^ state[2]
	state[0] = (state[0] + state[3]) & MASK_64
	state[3] = rotateLeft(state[3], 21n) ^ state[0]
	state[2] = (state[2] + state[1]) & MASK_64
	state[1] = rotateLeft(state[1], 17n) ^ state[2]
	state[2] = rotateLeft(state[2], 32n)
}

// Worktrunk uses Rust's DefaultHasher (SipHash 1-3 with zero keys).
function worktrunkHash(value: string): bigint {
	const bytes = Buffer.concat([Buffer.from(value), Buffer.from([0xff])])
	const state: SipState = [
		0x736f6d6570736575n,
		0x646f72616e646f6dn,
		0x6c7967656e657261n,
		0x7465646279746573n,
	]

	let offset = 0
	while (offset + 8 <= bytes.length) {
		const message = bytes.readBigUInt64LE(offset)
		state[3] ^= message
		sipRound(state)
		state[0] ^= message
		offset += 8
	}

	let tail = (BigInt(bytes.length) << 56n) & MASK_64
	for (let index = offset; index < bytes.length; index++) {
		tail |= BigInt(bytes.readUInt8(index)) << BigInt((index - offset) * 8)
	}

	state[3] ^= tail
	sipRound(state)
	state[0] ^= tail
	state[2] ^= 0xffn
	for (let round = 0; round < 3; round++) sipRound(state)

	return state[0] ^ state[1] ^ state[2] ^ state[3]
}

function hashPort(value: string): number {
	return 10_000 + Number(worktrunkHash(value) % 10_000n)
}

function shortHash(value: string): string {
	const characters = '0123456789abcdefghijklmnopqrstuvwxyz'
	const hash = worktrunkHash(value)
	return [hash % 36n, (hash / 36n) % 36n, (hash / 1296n) % 36n]
		.map((index) => characters[Number(index)])
		.join('')
}

function sanitizeDatabaseName(value: string): string {
	let result = value
		.replace(/[A-Z]/g, (character) => character.toLowerCase())
		.replace(/[^a-z0-9]+/g, '_')

	if (!result) return ''
	if (/^\d/.test(result)) result = `_${result}`
	result = result.slice(0, 44)
	if (!result.endsWith('_')) result += '_'

	return `${result}${shortHash(value)}`
}

function run(command: string, args: string[]): string {
	return execFileSync(command, args, {
		encoding: 'utf8',
		stdio: ['ignore', 'pipe', 'ignore'],
	}).trim()
}

function detectWorkspace(): { branch: string; worktree: string } {
	try {
		const root = realpathSync(run('jj', ['workspace', 'root']))
		const names = run('jj', [
			'workspace',
			'list',
			'-T',
			'self.name() ++ "\\n"',
		]).split('\n')
		const branch = names.find((name) => {
			try {
				return (
					realpathSync(run('jj', ['workspace', 'root', '--name', name])) ===
					root
				)
			} catch {
				return false
			}
		})

		if (!branch) throw new Error('Could not identify the current jj workspace')
		return { branch, worktree: basename(root) }
	} catch (error) {
		if (error instanceof Error && error.message.startsWith('Could not')) {
			throw error
		}
	}

	try {
		const root = realpathSync(run('git', ['rev-parse', '--show-toplevel']))
		const branch = run('git', ['branch', '--show-current']) || basename(root)
		return { branch, worktree: basename(root) }
	} catch {
		throw new Error('Run setup from inside a jj workspace or Git worktree')
	}
}

function updateEnvFile(path: string, updates: Record<string, string>): void {
	const lines = existsSync(path)
		? readFileSync(path, 'utf8').split(/\r?\n/)
		: []
	const remaining = new Set(Object.keys(updates))

	for (let index = 0; index < lines.length; index++) {
		const key = lines[index]?.match(/^\s*([^#=\s]+)\s*=/)?.[1]
		if (!key || !(key in updates)) continue

		lines[index] = `${key}="${updates[key]!}"`
		remaining.delete(key)
	}

	while (lines.at(-1) === '') lines.pop()
	if (remaining.size > 0) {
		if (lines.length > 0) lines.push('')
		lines.push('# AUTO-GENERATED BY vp run setup')
		for (const key of remaining) lines.push(`${key}="${updates[key]!}"`)
	}

	writeFileSync(path, `${lines.join('\n')}\n`)
}

function main(): void {
	const detected = detectWorkspace()
	const branch = process.env.WORKTREE_BRANCH || detected.branch
	const worktree = process.env.WORKTREE_NAME || detected.worktree
	const compose = sanitizeDatabaseName(worktree)
	const database = sanitizeDatabaseName(branch)
	const appPort = hashPort(branch)
	const postgresPort = hashPort(`db-${branch}`)
	const minioPort = hashPort(`minio-${branch}`)
	const minioConsolePort = hashPort(`minio-console-${branch}`)

	writeFileSync(
		'.env.compose',
		[
			'# AUTO-GENERATED BY vp run setup',
			`WORKTREE_NAME=${worktree}`,
			`COMPOSE_PROJECT_NAME=${compose}`,
			`APP_PORT=${appPort}`,
			`POSTGRES_PORT=${postgresPort}`,
			`POSTGRES_DB=${database}`,
			`MINIO_PORT=${minioPort}`,
			`MINIO_CONSOLE_PORT=${minioConsolePort}`,
			'',
		].join('\n'),
	)

	updateEnvFile('.env.development.local', {
		DATABASE_URL: `postgres://peace_user:peace_test@localhost:${postgresPort}/${database}`,
		AWS_ENDPOINT_URL: `http://localhost:${minioPort}`,
	})

	console.log(`Generated env files for ${branch}:`)
	console.log(`  app:      http://localhost:${appPort}`)
	console.log(`  postgres: localhost:${postgresPort}/${database}`)
	console.log(`  minio:    http://localhost:${minioPort}`)
}

main()
