import { createFileRoute } from '@tanstack/react-router'

import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import {
	CodeBlock,
	DocPage,
	DocSection,
	StepList,
} from '@/routes/docs/-components/doc-ui'

export const Route = createFileRoute('/docs/')({
	component: Overview,
})

const moduleTree = `src/
  db/
    tables.ts                       # existing — add introductions, swap entitlement keys
    migrations/0007_<name>.sql    # generated by drizzle-kit
  lib/
    matching/match.view.ts          # existing — add dimensions (score · weight · boosted)
    introductions/
      types.ts                      # row-derived aliases via $inferSelect
      guards.ts                     # pure guard predicates G1–G5
      views.ts                      # wire-safe view types + mappers
      db.ts                         # db ops (tx + advisory lock)
      server.ts                     # createServerFn wrappers, thin
      db.test.ts                    # guard boundaries, transitions, races
      views.test.ts                 # visibility: pre-connected views have NO contact keys
    payments/
      stripe.server.ts              # Stripe client
      intro-unlock.ts               # checkout creation + transactional fulfillment
      server.ts                     # createIntroUnlockCheckout
      intro-unlock.db.test.ts       # fulfillment, idempotency, connect-on-pay
    email.server.ts                 # existing — add the 5 intro templates
  routes/
    api/stripe-webhook.$.ts         # dispatch on event type + metadata.kind
    (dashboard)/
      _components/
        client-matches.tsx          # slot meter, selection, sticky send bar
        match-list.tsx              # rebuilt: toolbar, dense rows, inline expand
        client-introductions.tsx    # tabs, paywall, withdraw, unlock-success poll
        intro-paywall.tsx           # unlock banner + checkout redirect
      buyer/introductions.tsx       # render client-introductions
      seller/introductions.tsx      # render client-introductions
      agent/introductions.tsx       # fit cards, accept/decline modal
      agent/route.tsx               # add sidebar pending badge
    env.server.ts                   # add the 3 STRIPE_* vars
  tests/support/fixtures/data/      # add client/agent introduction fixtures
  e2e/introductions.spec.ts         # happy path`

function Overview() {
	return (
		<DocPage
			path="/docs"
			lede="Buyers and sellers see matched agents but have no safe way to start a
			conversation; agents won't accept blind leads. This feature gates
			contact exchange: clients request intros with 1–3 matched agents, agents
			review anonymous fit cards and accept or decline, and a $20 unlock opens
			a 6-month contact window. Matching and scoring are already built; the
			introduction table, email templates, and Stripe wiring are not."
		>
			<Card>
				<CardHeader>
					<CardTitle>Product loop</CardTitle>
				</CardHeader>
				<CardContent>
					<StepList
						steps={[
							<>
								Client selects 1–3 agents from their matches and sends
								introduction requests.
							</>,
							<>
								Each agent reviews an <b>anonymous fit card</b> (no contact
								info) and accepts or declines.
							</>,
							<>
								On first acceptance, the client can pay{' '}
								<b>$20 for a 6-month access window</b>.
							</>,
							<>
								Every acceptance during an active window becomes{' '}
								<b>connected</b>: full mutual contact exchange, in-app and by
								email.
							</>,
						]}
					/>
				</CardContent>
			</Card>

			<DocSection title="Out of scope (v1)">
				<p className="text-sm leading-relaxed">
					In-app messaging (the product deliberately ends at the introduction) ·
					client phone collection · saved payment methods / auto-charge on
					accept · refund self-service & admin tooling · agent-side capacity
					settings ("pause new intros") · intro analytics dashboards ·
					account-deletion sweeps.
				</p>
			</DocSection>

			<DocSection title="Module layout">
				<p className="text-muted-foreground text-sm">
					Domain logic lives in <code>src/lib/introductions/</code> as pure,
					db-parameterized functions; server functions stay thin; every wire
					payload leaves through <code>views.ts</code>. Everything below is new
					unless marked otherwise.
				</p>
				<CodeBlock code={moduleTree} language="tree" />
			</DocSection>
		</DocPage>
	)
}
