import type { ReactNode } from 'react'
import { Link, createFileRoute } from '@tanstack/react-router'

import {
	BulletList,
	CodeBlock,
	DocPage,
	DocSection,
} from '@/routes/docs/-components/doc-ui'

export const Route = createFileRoute('/docs/plan')({
	component: Plan,
})

type Phase = {
	num: string
	title: string
	body: ReactNode
	files?: string[]
	commit?: string
	gate: string
	dependsOn?: string
}

const moduleTree = `src/
  db/
    tables.ts                       # add introductions, swap entitlement keys
    migrations/0007_<name>.sql      # generated by drizzle-kit
  lib/
    matching/match.view.ts          # add dimensions (score · weight · boosted)
    introductions/
      types.ts
      guards.ts
      views.ts
      db.ts
      server.ts
      db.test.ts
      views.test.ts
    payments/
      stripe.server.ts
      intro-unlock.ts
      server.ts
      intro-unlock.db.test.ts
    email.server.ts                 # add 5 intro templates
  routes/
    api/stripe-webhook.$.ts
    (dashboard)/
      _components/
        client-matches.tsx
        match-list.tsx
        client-introductions.tsx
        intro-paywall.tsx
      buyer/introductions.tsx
      seller/introductions.tsx
      agent/introductions.tsx
      agent/route.tsx
  env.server.ts
  tests/support/fixtures/data/
  e2e/introductions.spec.ts`

const tracks = [
	{
		name: 'Foundation',
		summary:
			'Schema, domain logic, and thin server functions before any UI or money work.',
		phases: ['1', '2', '3'],
	},
	{
		name: 'Monetization',
		summary: 'Stripe checkout, webhook fulfillment, and connected emails.',
		phases: ['4'],
	},
	{
		name: 'Surfaces',
		summary: 'The match list, client page, and agent UI.',
		phases: ['5', '6', '7'],
	},
	{
		name: 'Assurance',
		summary: 'End-to-end coverage and repository cleanup.',
		phases: ['8'],
	},
]

const phases: Phase[] = [
	{
		num: '1',
		title: 'Schema & migration',
		body: (
			<>
				Add the <code>introductions</code> table, enum, indexes, and swap the
				entitlement keys for buyer/seller access windows. Hand-write migration
				0007. See{' '}
				<Link to="/docs/lifecycle" className="underline">
					Lifecycle
				</Link>{' '}
				for the schema and{' '}
				<Link to="/docs/payments" className="underline">
					Payments
				</Link>{' '}
				for entitlements.
			</>
		),
		files: ['src/db/tables.ts', 'src/db/migrations/0007_*.sql'],
		commit: 'feat(intros): introductions schema and migration 0007',
		gate: 'vp check · vp test',
	},
	{
		num: '2',
		title: 'Domain library',
		body: (
			<>
				<code>types.ts</code>, <code>guards.ts</code>, <code>views.ts</code>,{' '}
				<code>db.ts</code>. Pure guard predicates G1–G5, view mappers, and db
				operations with advisory locking. See{' '}
				<Link to="/docs/lifecycle" className="underline">
					Lifecycle
				</Link>{' '}
				for state/visibility,{' '}
				<Link to="/docs/anti-abuse" className="underline">
					Anti-abuse
				</Link>{' '}
				for guards, and{' '}
				<Link to="/docs/payments" className="underline">
					Payments
				</Link>{' '}
				for fulfillment types.
			</>
		),
		files: [
			'src/lib/introductions/types.ts',
			'src/lib/introductions/guards.ts',
			'src/lib/introductions/views.ts',
			'src/lib/introductions/db.ts',
		],
		commit: 'feat(intros): domain library with guards and view shaping',
		gate: 'vp check · vp test',
		dependsOn: '1',
	},
	{
		num: '3',
		title: 'Server functions',
		body: (
			<>
				<code>server.ts</code> wrappers, auth checks, zod validators. See{' '}
				<Link to="/docs/lifecycle" className="underline">
					Lifecycle
				</Link>{' '}
				for lifecycle functions and{' '}
				<Link to="/docs/payments" className="underline">
					Payments
				</Link>{' '}
				for checkout/fulfillment.
			</>
		),
		files: [
			'src/lib/introductions/server.ts',
			'src/lib/introductions/db.test.ts',
			'src/lib/introductions/views.test.ts',
		],
		commit: 'feat(intros): server functions',
		gate: 'vp check · vp test',
		dependsOn: '2',
	},
	{
		num: '4',
		title: 'Payments & fulfillment',
		body: (
			<>
				Stripe client, checkout, webhook dispatch, and transactional
				fulfillment. Fulfillment connects accepted intros and queues the
				connected emails. See{' '}
				<Link to="/docs/payments" className="underline">
					Payments
				</Link>{' '}
				for details and{' '}
				<Link to="/docs/lifecycle" className="underline">
					Lifecycle
				</Link>{' '}
				for email templates.
			</>
		),
		files: [
			'src/lib/payments/stripe.server.ts',
			'src/lib/payments/intro-unlock.ts',
			'src/lib/payments/server.ts',
			'src/lib/payments/intro-unlock.db.test.ts',
			'src/lib/email.server.ts',
		],
		commit: 'feat(intros): $20 unlock window with Stripe fulfillment',
		gate: 'vp check · vp test',
		dependsOn: '3',
	},
	{
		num: '5',
		title: 'Match list redesign & send flow',
		body: (
			<>
				Rebuild the match list as a compact decision surface and wire the send
				flow. Sends the first intro email and updates slot math live. See{' '}
				<Link to="/docs/ui" className="underline">
					UI
				</Link>{' '}
				for the match list redesign and component plan.
			</>
		),
		files: [
			'src/routes/(dashboard)/_components/client-matches.tsx',
			'src/routes/(dashboard)/_components/match-list.tsx',
		],
		commit: 'feat(intros): match list redesign with selection and send flow',
		gate: 'vp check · vp test',
		dependsOn: '3',
	},
	{
		num: '6',
		title: 'Client introductions page',
		body: (
			<>
				Tabs, paywall, withdraw countdown, and unlock-success poll. See{' '}
				<Link to="/docs/ui" className="underline">
					UI
				</Link>{' '}
				for the client introductions surface.
			</>
		),
		files: [
			'src/routes/(dashboard)/_components/client-introductions.tsx',
			'src/routes/(dashboard)/_components/intro-paywall.tsx',
			'src/routes/(dashboard)/buyer/introductions.tsx',
			'src/routes/(dashboard)/seller/introductions.tsx',
		],
		commit: 'feat(intros): client introductions page with unlock flow',
		gate: 'vp check · vp test',
		dependsOn: '4',
	},
	{
		num: '7',
		title: 'Agent introductions UI',
		body: (
			<>
				Fit cards, accept/decline modal, and pending badge. See{' '}
				<Link to="/docs/ui" className="underline">
					UI
				</Link>{' '}
				for the agent introductions surface.
			</>
		),
		files: [
			'src/routes/(dashboard)/_components/agent-introductions.tsx',
			'src/routes/(dashboard)/agent/introductions.tsx',
			'src/routes/(dashboard)/agent/route.tsx',
		],
		commit: 'feat(intros): agent introductions UI',
		gate: 'vp check · vp test',
		dependsOn: '3',
	},
	{
		num: '8',
		title: 'E2E & cleanup',
		body: (
			<>
				Playwright happy path: send → agent accepts → stubbed pay → both sides
				see contact info. knip clean; no dead exports.
			</>
		),
		files: ['tests/e2e/introductions.spec.ts', 'knip.config.ts'],
		commit: 'feat(intros): e2e coverage and cleanup',
		gate: 'vp check · vp test · vp run e2e',
		dependsOn: '5 · 6 · 7',
	},
]

function TrackBadge({ name }: { name: string }) {
	return (
		<span className="bg-muted text-muted-foreground rounded-md px-2 py-1 text-xs font-semibold tracking-wider uppercase">
			{name}
		</span>
	)
}

function TrackHeader({ track }: { track: (typeof tracks)[number] }) {
	return (
		<div className="space-y-1">
			<div className="flex items-center gap-2">
				<TrackBadge name={track.name} />
				<span className="text-muted-foreground text-xs">
					phases {track.phases.join('–')}
				</span>
			</div>
			<p className="text-muted-foreground text-sm">{track.summary}</p>
		</div>
	)
}

function PhaseRow({ phase }: { phase: Phase }) {
	const isDone = phase.num === '✓'
	return (
		<div className="flex gap-4 border-b border-dashed py-5 last:border-b-0">
			<div
				className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-lg text-sm font-extrabold ${
					isDone
						? 'border border-emerald-600/40 bg-emerald-600/10 text-emerald-700'
						: 'bg-primary text-primary-foreground'
				}`}
			>
				{phase.num}
			</div>
			<div className="min-w-0 flex-1">
				<h3 className="text-base font-bold">{phase.title}</h3>
				<p className="mt-1 text-sm leading-relaxed">{phase.body}</p>
				{phase.files ? (
					<div className="mt-3 flex flex-wrap gap-1.5">
						{phase.files.map((file) => (
							<code
								key={file}
								className="bg-muted text-muted-foreground rounded px-1.5 py-0.5 text-[11px]"
							>
								{file}
							</code>
						))}
					</div>
				) : null}
				{phase.commit ? (
					<div className="mt-3 inline-flex items-center rounded-md border border-emerald-600/40 bg-emerald-600/10 px-2.5 py-1 font-mono text-xs text-emerald-700">
						{phase.commit}
					</div>
				) : null}
				<div className="text-muted-foreground mt-2 flex flex-wrap items-center gap-x-3 gap-y-1 font-mono text-xs">
					<span>gate: {phase.gate}</span>
					{phase.dependsOn ? <span>depends on: {phase.dependsOn}</span> : null}
				</div>
			</div>
		</div>
	)
}

function Plan() {
	return (
		<DocPage
			path="/docs/plan"
			lede="How the spec gets built on this branch: 8 phases — one commit each. Foundation and monetization run first, then the three UI surfaces in parallel, then e2e."
		>
			<DocSection title="Module layout">
				<p className="text-muted-foreground text-sm">
					Domain logic in <code>src/lib/introductions/</code> and{' '}
					<code>src/lib/payments/</code>; surfaces in the dashboard route tree.
					Everything below is new unless marked.
				</p>
				<CodeBlock code={moduleTree} language="tree" />
			</DocSection>

			<DocSection title="Tracks">
				<div className="space-y-4">
					{tracks.map((track) => (
						<TrackHeader key={track.name} track={track} />
					))}
				</div>
			</DocSection>

			<DocSection title="Phases — one commit each">
				<div className="divide-y">
					{phases.map((phase) => (
						<PhaseRow key={phase.num} phase={phase} />
					))}
				</div>
			</DocSection>

			<DocSection title="Risks & notes">
				<BulletList>
					<li>
						<b>Price-bucket fix:</b> G4 eligibility depends on the matching
						engine's price-bucket calculation being fixed before Phase 2.
					</li>
					<li>
						<b>Match list refactor:</b> Phase 5 is the largest UI change; it
						runs after the domain is stable so it isn't rebuilt against a moving
						server contract.
					</li>
					<li>
						<b>Stripe environment:</b> Phase 4 needs a working test price and
						webhook secret before the happy-path e2e in Phase 8 can pass.
					</li>
				</BulletList>
			</DocSection>
		</DocPage>
	)
}
