/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthCompleteRouteImport } from './routes/auth/complete'
import { Route as AuthBetaRouteImport } from './routes/auth/beta'
import { Route as dashboardSellerRouteRouteImport } from './routes/(dashboard)/seller/route'
import { Route as dashboardBuyerRouteRouteImport } from './routes/(dashboard)/buyer/route'
import { Route as dashboardAgentRouteRouteImport } from './routes/(dashboard)/agent/route'
import { Route as SignupPreviewSellerRouteImport } from './routes/signup/preview/seller'
import { Route as SignupPreviewBuyerRouteImport } from './routes/signup/preview/buyer'
import { Route as SignupPreviewAgentRouteImport } from './routes/signup/preview/agent'
import { Route as ApiIngestSplatRouteImport } from './routes/api/ingest.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as dashboardSellerSearchPreferencesRouteImport } from './routes/(dashboard)/seller/search-preferences'
import { Route as dashboardSellerPracticeNegotiatingRouteImport } from './routes/(dashboard)/seller/practice-negotiating'
import { Route as dashboardSellerMatchesRouteImport } from './routes/(dashboard)/seller/matches'
import { Route as dashboardSellerIntroductionsRouteImport } from './routes/(dashboard)/seller/introductions'
import { Route as dashboardBuyerSearchPreferencesRouteImport } from './routes/(dashboard)/buyer/search-preferences'
import { Route as dashboardBuyerPracticeNegotiatingRouteImport } from './routes/(dashboard)/buyer/practice-negotiating'
import { Route as dashboardBuyerMatchesRouteImport } from './routes/(dashboard)/buyer/matches'
import { Route as dashboardBuyerIntroductionsRouteImport } from './routes/(dashboard)/buyer/introductions'
import { Route as dashboardAgentIntroductionsRouteImport } from './routes/(dashboard)/agent/introductions'
import { Route as SignupstepsSellerRouteRouteImport } from './routes/signup/(steps)/seller/route'
import { Route as SignupstepsBuyerRouteRouteImport } from './routes/signup/(steps)/buyer/route'
import { Route as SignupstepsAgentRouteRouteImport } from './routes/signup/(steps)/agent/route'
import { Route as ApiIngestStaticSplatRouteImport } from './routes/api/ingest.static.$'
import { Route as SignupstepsSellerstep3PreferencesRouteImport } from './routes/signup/(steps)/seller/(step-3).preferences'
import { Route as SignupstepsSellerstep2LocationRouteImport } from './routes/signup/(steps)/seller/(step-2).location'
import { Route as SignupstepsSellerstep1HomeRouteImport } from './routes/signup/(steps)/seller/(step-1).home'
import { Route as SignupstepsBuyerstep3PreferencesRouteImport } from './routes/signup/(steps)/buyer/(step-3).preferences'
import { Route as SignupstepsBuyerstep2LocationRouteImport } from './routes/signup/(steps)/buyer/(step-2).location'
import { Route as SignupstepsBuyerstep1HomeRouteImport } from './routes/signup/(steps)/buyer/(step-1).home'
import { Route as SignupstepsAgentstep5PeacePactRouteImport } from './routes/signup/(steps)/agent/(step-5).peace-pact'
import { Route as SignupstepsAgentstep4ComplianceRouteImport } from './routes/signup/(steps)/agent/(step-4).compliance'
import { Route as SignupstepsAgentstep3PreferencesRouteImport } from './routes/signup/(steps)/agent/(step-3).preferences'
import { Route as SignupstepsAgentstep2MarketRouteImport } from './routes/signup/(steps)/agent/(step-2).market'
import { Route as SignupstepsAgentstep1IdentityRouteImport } from './routes/signup/(steps)/agent/(step-1).identity'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompleteRoute = AuthCompleteRouteImport.update({
  id: '/auth/complete',
  path: '/auth/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthBetaRoute = AuthBetaRouteImport.update({
  id: '/auth/beta',
  path: '/auth/beta',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardSellerRouteRoute = dashboardSellerRouteRouteImport.update({
  id: '/(dashboard)/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardBuyerRouteRoute = dashboardBuyerRouteRouteImport.update({
  id: '/(dashboard)/buyer',
  path: '/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardAgentRouteRoute = dashboardAgentRouteRouteImport.update({
  id: '/(dashboard)/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupPreviewSellerRoute = SignupPreviewSellerRouteImport.update({
  id: '/signup/preview/seller',
  path: '/signup/preview/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupPreviewBuyerRoute = SignupPreviewBuyerRouteImport.update({
  id: '/signup/preview/buyer',
  path: '/signup/preview/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupPreviewAgentRoute = SignupPreviewAgentRouteImport.update({
  id: '/signup/preview/agent',
  path: '/signup/preview/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestSplatRoute = ApiIngestSplatRouteImport.update({
  id: '/api/ingest/$',
  path: '/api/ingest/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardSellerSearchPreferencesRoute =
  dashboardSellerSearchPreferencesRouteImport.update({
    id: '/search-preferences',
    path: '/search-preferences',
    getParentRoute: () => dashboardSellerRouteRoute,
  } as any)
const dashboardSellerPracticeNegotiatingRoute =
  dashboardSellerPracticeNegotiatingRouteImport.update({
    id: '/practice-negotiating',
    path: '/practice-negotiating',
    getParentRoute: () => dashboardSellerRouteRoute,
  } as any)
const dashboardSellerMatchesRoute = dashboardSellerMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => dashboardSellerRouteRoute,
} as any)
const dashboardSellerIntroductionsRoute =
  dashboardSellerIntroductionsRouteImport.update({
    id: '/introductions',
    path: '/introductions',
    getParentRoute: () => dashboardSellerRouteRoute,
  } as any)
const dashboardBuyerSearchPreferencesRoute =
  dashboardBuyerSearchPreferencesRouteImport.update({
    id: '/search-preferences',
    path: '/search-preferences',
    getParentRoute: () => dashboardBuyerRouteRoute,
  } as any)
const dashboardBuyerPracticeNegotiatingRoute =
  dashboardBuyerPracticeNegotiatingRouteImport.update({
    id: '/practice-negotiating',
    path: '/practice-negotiating',
    getParentRoute: () => dashboardBuyerRouteRoute,
  } as any)
const dashboardBuyerMatchesRoute = dashboardBuyerMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => dashboardBuyerRouteRoute,
} as any)
const dashboardBuyerIntroductionsRoute =
  dashboardBuyerIntroductionsRouteImport.update({
    id: '/introductions',
    path: '/introductions',
    getParentRoute: () => dashboardBuyerRouteRoute,
  } as any)
const dashboardAgentIntroductionsRoute =
  dashboardAgentIntroductionsRouteImport.update({
    id: '/introductions',
    path: '/introductions',
    getParentRoute: () => dashboardAgentRouteRoute,
  } as any)
const SignupstepsSellerRouteRoute = SignupstepsSellerRouteRouteImport.update({
  id: '/signup/(steps)/seller',
  path: '/signup/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupstepsBuyerRouteRoute = SignupstepsBuyerRouteRouteImport.update({
  id: '/signup/(steps)/buyer',
  path: '/signup/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupstepsAgentRouteRoute = SignupstepsAgentRouteRouteImport.update({
  id: '/signup/(steps)/agent',
  path: '/signup/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestStaticSplatRoute = ApiIngestStaticSplatRouteImport.update({
  id: '/api/ingest/static/$',
  path: '/api/ingest/static/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupstepsSellerstep3PreferencesRoute =
  SignupstepsSellerstep3PreferencesRouteImport.update({
    id: '/(step-3)/preferences',
    path: '/preferences',
    getParentRoute: () => SignupstepsSellerRouteRoute,
  } as any)
const SignupstepsSellerstep2LocationRoute =
  SignupstepsSellerstep2LocationRouteImport.update({
    id: '/(step-2)/location',
    path: '/location',
    getParentRoute: () => SignupstepsSellerRouteRoute,
  } as any)
const SignupstepsSellerstep1HomeRoute =
  SignupstepsSellerstep1HomeRouteImport.update({
    id: '/(step-1)/home',
    path: '/home',
    getParentRoute: () => SignupstepsSellerRouteRoute,
  } as any)
const SignupstepsBuyerstep3PreferencesRoute =
  SignupstepsBuyerstep3PreferencesRouteImport.update({
    id: '/(step-3)/preferences',
    path: '/preferences',
    getParentRoute: () => SignupstepsBuyerRouteRoute,
  } as any)
const SignupstepsBuyerstep2LocationRoute =
  SignupstepsBuyerstep2LocationRouteImport.update({
    id: '/(step-2)/location',
    path: '/location',
    getParentRoute: () => SignupstepsBuyerRouteRoute,
  } as any)
const SignupstepsBuyerstep1HomeRoute =
  SignupstepsBuyerstep1HomeRouteImport.update({
    id: '/(step-1)/home',
    path: '/home',
    getParentRoute: () => SignupstepsBuyerRouteRoute,
  } as any)
const SignupstepsAgentstep5PeacePactRoute =
  SignupstepsAgentstep5PeacePactRouteImport.update({
    id: '/(step-5)/peace-pact',
    path: '/peace-pact',
    getParentRoute: () => SignupstepsAgentRouteRoute,
  } as any)
const SignupstepsAgentstep4ComplianceRoute =
  SignupstepsAgentstep4ComplianceRouteImport.update({
    id: '/(step-4)/compliance',
    path: '/compliance',
    getParentRoute: () => SignupstepsAgentRouteRoute,
  } as any)
const SignupstepsAgentstep3PreferencesRoute =
  SignupstepsAgentstep3PreferencesRouteImport.update({
    id: '/(step-3)/preferences',
    path: '/preferences',
    getParentRoute: () => SignupstepsAgentRouteRoute,
  } as any)
const SignupstepsAgentstep2MarketRoute =
  SignupstepsAgentstep2MarketRouteImport.update({
    id: '/(step-2)/market',
    path: '/market',
    getParentRoute: () => SignupstepsAgentRouteRoute,
  } as any)
const SignupstepsAgentstep1IdentityRoute =
  SignupstepsAgentstep1IdentityRouteImport.update({
    id: '/(step-1)/identity',
    path: '/identity',
    getParentRoute: () => SignupstepsAgentRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof dashboardAgentRouteRouteWithChildren
  '/buyer': typeof dashboardBuyerRouteRouteWithChildren
  '/seller': typeof dashboardSellerRouteRouteWithChildren
  '/auth/beta': typeof AuthBetaRoute
  '/auth/complete': typeof AuthCompleteRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/signup/agent': typeof SignupstepsAgentRouteRouteWithChildren
  '/signup/buyer': typeof SignupstepsBuyerRouteRouteWithChildren
  '/signup/seller': typeof SignupstepsSellerRouteRouteWithChildren
  '/agent/introductions': typeof dashboardAgentIntroductionsRoute
  '/buyer/introductions': typeof dashboardBuyerIntroductionsRoute
  '/buyer/matches': typeof dashboardBuyerMatchesRoute
  '/buyer/practice-negotiating': typeof dashboardBuyerPracticeNegotiatingRoute
  '/buyer/search-preferences': typeof dashboardBuyerSearchPreferencesRoute
  '/seller/introductions': typeof dashboardSellerIntroductionsRoute
  '/seller/matches': typeof dashboardSellerMatchesRoute
  '/seller/practice-negotiating': typeof dashboardSellerPracticeNegotiatingRoute
  '/seller/search-preferences': typeof dashboardSellerSearchPreferencesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ingest/$': typeof ApiIngestSplatRoute
  '/signup/preview/agent': typeof SignupPreviewAgentRoute
  '/signup/preview/buyer': typeof SignupPreviewBuyerRoute
  '/signup/preview/seller': typeof SignupPreviewSellerRoute
  '/api/ingest/static/$': typeof ApiIngestStaticSplatRoute
  '/signup/agent/identity': typeof SignupstepsAgentstep1IdentityRoute
  '/signup/agent/market': typeof SignupstepsAgentstep2MarketRoute
  '/signup/agent/preferences': typeof SignupstepsAgentstep3PreferencesRoute
  '/signup/agent/compliance': typeof SignupstepsAgentstep4ComplianceRoute
  '/signup/agent/peace-pact': typeof SignupstepsAgentstep5PeacePactRoute
  '/signup/buyer/home': typeof SignupstepsBuyerstep1HomeRoute
  '/signup/buyer/location': typeof SignupstepsBuyerstep2LocationRoute
  '/signup/buyer/preferences': typeof SignupstepsBuyerstep3PreferencesRoute
  '/signup/seller/home': typeof SignupstepsSellerstep1HomeRoute
  '/signup/seller/location': typeof SignupstepsSellerstep2LocationRoute
  '/signup/seller/preferences': typeof SignupstepsSellerstep3PreferencesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof dashboardAgentRouteRouteWithChildren
  '/buyer': typeof dashboardBuyerRouteRouteWithChildren
  '/seller': typeof dashboardSellerRouteRouteWithChildren
  '/auth/beta': typeof AuthBetaRoute
  '/auth/complete': typeof AuthCompleteRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/signup/agent': typeof SignupstepsAgentRouteRouteWithChildren
  '/signup/buyer': typeof SignupstepsBuyerRouteRouteWithChildren
  '/signup/seller': typeof SignupstepsSellerRouteRouteWithChildren
  '/agent/introductions': typeof dashboardAgentIntroductionsRoute
  '/buyer/introductions': typeof dashboardBuyerIntroductionsRoute
  '/buyer/matches': typeof dashboardBuyerMatchesRoute
  '/buyer/practice-negotiating': typeof dashboardBuyerPracticeNegotiatingRoute
  '/buyer/search-preferences': typeof dashboardBuyerSearchPreferencesRoute
  '/seller/introductions': typeof dashboardSellerIntroductionsRoute
  '/seller/matches': typeof dashboardSellerMatchesRoute
  '/seller/practice-negotiating': typeof dashboardSellerPracticeNegotiatingRoute
  '/seller/search-preferences': typeof dashboardSellerSearchPreferencesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ingest/$': typeof ApiIngestSplatRoute
  '/signup/preview/agent': typeof SignupPreviewAgentRoute
  '/signup/preview/buyer': typeof SignupPreviewBuyerRoute
  '/signup/preview/seller': typeof SignupPreviewSellerRoute
  '/api/ingest/static/$': typeof ApiIngestStaticSplatRoute
  '/signup/agent/identity': typeof SignupstepsAgentstep1IdentityRoute
  '/signup/agent/market': typeof SignupstepsAgentstep2MarketRoute
  '/signup/agent/preferences': typeof SignupstepsAgentstep3PreferencesRoute
  '/signup/agent/compliance': typeof SignupstepsAgentstep4ComplianceRoute
  '/signup/agent/peace-pact': typeof SignupstepsAgentstep5PeacePactRoute
  '/signup/buyer/home': typeof SignupstepsBuyerstep1HomeRoute
  '/signup/buyer/location': typeof SignupstepsBuyerstep2LocationRoute
  '/signup/buyer/preferences': typeof SignupstepsBuyerstep3PreferencesRoute
  '/signup/seller/home': typeof SignupstepsSellerstep1HomeRoute
  '/signup/seller/location': typeof SignupstepsSellerstep2LocationRoute
  '/signup/seller/preferences': typeof SignupstepsSellerstep3PreferencesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(dashboard)/agent': typeof dashboardAgentRouteRouteWithChildren
  '/(dashboard)/buyer': typeof dashboardBuyerRouteRouteWithChildren
  '/(dashboard)/seller': typeof dashboardSellerRouteRouteWithChildren
  '/auth/beta': typeof AuthBetaRoute
  '/auth/complete': typeof AuthCompleteRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/signup/(steps)/agent': typeof SignupstepsAgentRouteRouteWithChildren
  '/signup/(steps)/buyer': typeof SignupstepsBuyerRouteRouteWithChildren
  '/signup/(steps)/seller': typeof SignupstepsSellerRouteRouteWithChildren
  '/(dashboard)/agent/introductions': typeof dashboardAgentIntroductionsRoute
  '/(dashboard)/buyer/introductions': typeof dashboardBuyerIntroductionsRoute
  '/(dashboard)/buyer/matches': typeof dashboardBuyerMatchesRoute
  '/(dashboard)/buyer/practice-negotiating': typeof dashboardBuyerPracticeNegotiatingRoute
  '/(dashboard)/buyer/search-preferences': typeof dashboardBuyerSearchPreferencesRoute
  '/(dashboard)/seller/introductions': typeof dashboardSellerIntroductionsRoute
  '/(dashboard)/seller/matches': typeof dashboardSellerMatchesRoute
  '/(dashboard)/seller/practice-negotiating': typeof dashboardSellerPracticeNegotiatingRoute
  '/(dashboard)/seller/search-preferences': typeof dashboardSellerSearchPreferencesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ingest/$': typeof ApiIngestSplatRoute
  '/signup/preview/agent': typeof SignupPreviewAgentRoute
  '/signup/preview/buyer': typeof SignupPreviewBuyerRoute
  '/signup/preview/seller': typeof SignupPreviewSellerRoute
  '/api/ingest/static/$': typeof ApiIngestStaticSplatRoute
  '/signup/(steps)/agent/(step-1)/identity': typeof SignupstepsAgentstep1IdentityRoute
  '/signup/(steps)/agent/(step-2)/market': typeof SignupstepsAgentstep2MarketRoute
  '/signup/(steps)/agent/(step-3)/preferences': typeof SignupstepsAgentstep3PreferencesRoute
  '/signup/(steps)/agent/(step-4)/compliance': typeof SignupstepsAgentstep4ComplianceRoute
  '/signup/(steps)/agent/(step-5)/peace-pact': typeof SignupstepsAgentstep5PeacePactRoute
  '/signup/(steps)/buyer/(step-1)/home': typeof SignupstepsBuyerstep1HomeRoute
  '/signup/(steps)/buyer/(step-2)/location': typeof SignupstepsBuyerstep2LocationRoute
  '/signup/(steps)/buyer/(step-3)/preferences': typeof SignupstepsBuyerstep3PreferencesRoute
  '/signup/(steps)/seller/(step-1)/home': typeof SignupstepsSellerstep1HomeRoute
  '/signup/(steps)/seller/(step-2)/location': typeof SignupstepsSellerstep2LocationRoute
  '/signup/(steps)/seller/(step-3)/preferences': typeof SignupstepsSellerstep3PreferencesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/buyer'
    | '/seller'
    | '/auth/beta'
    | '/auth/complete'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/signup/agent'
    | '/signup/buyer'
    | '/signup/seller'
    | '/agent/introductions'
    | '/buyer/introductions'
    | '/buyer/matches'
    | '/buyer/practice-negotiating'
    | '/buyer/search-preferences'
    | '/seller/introductions'
    | '/seller/matches'
    | '/seller/practice-negotiating'
    | '/seller/search-preferences'
    | '/api/auth/$'
    | '/api/ingest/$'
    | '/signup/preview/agent'
    | '/signup/preview/buyer'
    | '/signup/preview/seller'
    | '/api/ingest/static/$'
    | '/signup/agent/identity'
    | '/signup/agent/market'
    | '/signup/agent/preferences'
    | '/signup/agent/compliance'
    | '/signup/agent/peace-pact'
    | '/signup/buyer/home'
    | '/signup/buyer/location'
    | '/signup/buyer/preferences'
    | '/signup/seller/home'
    | '/signup/seller/location'
    | '/signup/seller/preferences'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/buyer'
    | '/seller'
    | '/auth/beta'
    | '/auth/complete'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/signup/agent'
    | '/signup/buyer'
    | '/signup/seller'
    | '/agent/introductions'
    | '/buyer/introductions'
    | '/buyer/matches'
    | '/buyer/practice-negotiating'
    | '/buyer/search-preferences'
    | '/seller/introductions'
    | '/seller/matches'
    | '/seller/practice-negotiating'
    | '/seller/search-preferences'
    | '/api/auth/$'
    | '/api/ingest/$'
    | '/signup/preview/agent'
    | '/signup/preview/buyer'
    | '/signup/preview/seller'
    | '/api/ingest/static/$'
    | '/signup/agent/identity'
    | '/signup/agent/market'
    | '/signup/agent/preferences'
    | '/signup/agent/compliance'
    | '/signup/agent/peace-pact'
    | '/signup/buyer/home'
    | '/signup/buyer/location'
    | '/signup/buyer/preferences'
    | '/signup/seller/home'
    | '/signup/seller/location'
    | '/signup/seller/preferences'
  id:
    | '__root__'
    | '/'
    | '/(dashboard)/agent'
    | '/(dashboard)/buyer'
    | '/(dashboard)/seller'
    | '/auth/beta'
    | '/auth/complete'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/signup/(steps)/agent'
    | '/signup/(steps)/buyer'
    | '/signup/(steps)/seller'
    | '/(dashboard)/agent/introductions'
    | '/(dashboard)/buyer/introductions'
    | '/(dashboard)/buyer/matches'
    | '/(dashboard)/buyer/practice-negotiating'
    | '/(dashboard)/buyer/search-preferences'
    | '/(dashboard)/seller/introductions'
    | '/(dashboard)/seller/matches'
    | '/(dashboard)/seller/practice-negotiating'
    | '/(dashboard)/seller/search-preferences'
    | '/api/auth/$'
    | '/api/ingest/$'
    | '/signup/preview/agent'
    | '/signup/preview/buyer'
    | '/signup/preview/seller'
    | '/api/ingest/static/$'
    | '/signup/(steps)/agent/(step-1)/identity'
    | '/signup/(steps)/agent/(step-2)/market'
    | '/signup/(steps)/agent/(step-3)/preferences'
    | '/signup/(steps)/agent/(step-4)/compliance'
    | '/signup/(steps)/agent/(step-5)/peace-pact'
    | '/signup/(steps)/buyer/(step-1)/home'
    | '/signup/(steps)/buyer/(step-2)/location'
    | '/signup/(steps)/buyer/(step-3)/preferences'
    | '/signup/(steps)/seller/(step-1)/home'
    | '/signup/(steps)/seller/(step-2)/location'
    | '/signup/(steps)/seller/(step-3)/preferences'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  dashboardAgentRouteRoute: typeof dashboardAgentRouteRouteWithChildren
  dashboardBuyerRouteRoute: typeof dashboardBuyerRouteRouteWithChildren
  dashboardSellerRouteRoute: typeof dashboardSellerRouteRouteWithChildren
  AuthBetaRoute: typeof AuthBetaRoute
  AuthCompleteRoute: typeof AuthCompleteRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  SignupstepsAgentRouteRoute: typeof SignupstepsAgentRouteRouteWithChildren
  SignupstepsBuyerRouteRoute: typeof SignupstepsBuyerRouteRouteWithChildren
  SignupstepsSellerRouteRoute: typeof SignupstepsSellerRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiIngestSplatRoute: typeof ApiIngestSplatRoute
  SignupPreviewAgentRoute: typeof SignupPreviewAgentRoute
  SignupPreviewBuyerRoute: typeof SignupPreviewBuyerRoute
  SignupPreviewSellerRoute: typeof SignupPreviewSellerRoute
  ApiIngestStaticSplatRoute: typeof ApiIngestStaticSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/complete': {
      id: '/auth/complete'
      path: '/auth/complete'
      fullPath: '/auth/complete'
      preLoaderRoute: typeof AuthCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/beta': {
      id: '/auth/beta'
      path: '/auth/beta'
      fullPath: '/auth/beta'
      preLoaderRoute: typeof AuthBetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/seller': {
      id: '/(dashboard)/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof dashboardSellerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/buyer': {
      id: '/(dashboard)/buyer'
      path: '/buyer'
      fullPath: '/buyer'
      preLoaderRoute: typeof dashboardBuyerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/agent': {
      id: '/(dashboard)/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof dashboardAgentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/preview/seller': {
      id: '/signup/preview/seller'
      path: '/signup/preview/seller'
      fullPath: '/signup/preview/seller'
      preLoaderRoute: typeof SignupPreviewSellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/preview/buyer': {
      id: '/signup/preview/buyer'
      path: '/signup/preview/buyer'
      fullPath: '/signup/preview/buyer'
      preLoaderRoute: typeof SignupPreviewBuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/preview/agent': {
      id: '/signup/preview/agent'
      path: '/signup/preview/agent'
      fullPath: '/signup/preview/agent'
      preLoaderRoute: typeof SignupPreviewAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest/$': {
      id: '/api/ingest/$'
      path: '/api/ingest/$'
      fullPath: '/api/ingest/$'
      preLoaderRoute: typeof ApiIngestSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/seller/search-preferences': {
      id: '/(dashboard)/seller/search-preferences'
      path: '/search-preferences'
      fullPath: '/seller/search-preferences'
      preLoaderRoute: typeof dashboardSellerSearchPreferencesRouteImport
      parentRoute: typeof dashboardSellerRouteRoute
    }
    '/(dashboard)/seller/practice-negotiating': {
      id: '/(dashboard)/seller/practice-negotiating'
      path: '/practice-negotiating'
      fullPath: '/seller/practice-negotiating'
      preLoaderRoute: typeof dashboardSellerPracticeNegotiatingRouteImport
      parentRoute: typeof dashboardSellerRouteRoute
    }
    '/(dashboard)/seller/matches': {
      id: '/(dashboard)/seller/matches'
      path: '/matches'
      fullPath: '/seller/matches'
      preLoaderRoute: typeof dashboardSellerMatchesRouteImport
      parentRoute: typeof dashboardSellerRouteRoute
    }
    '/(dashboard)/seller/introductions': {
      id: '/(dashboard)/seller/introductions'
      path: '/introductions'
      fullPath: '/seller/introductions'
      preLoaderRoute: typeof dashboardSellerIntroductionsRouteImport
      parentRoute: typeof dashboardSellerRouteRoute
    }
    '/(dashboard)/buyer/search-preferences': {
      id: '/(dashboard)/buyer/search-preferences'
      path: '/search-preferences'
      fullPath: '/buyer/search-preferences'
      preLoaderRoute: typeof dashboardBuyerSearchPreferencesRouteImport
      parentRoute: typeof dashboardBuyerRouteRoute
    }
    '/(dashboard)/buyer/practice-negotiating': {
      id: '/(dashboard)/buyer/practice-negotiating'
      path: '/practice-negotiating'
      fullPath: '/buyer/practice-negotiating'
      preLoaderRoute: typeof dashboardBuyerPracticeNegotiatingRouteImport
      parentRoute: typeof dashboardBuyerRouteRoute
    }
    '/(dashboard)/buyer/matches': {
      id: '/(dashboard)/buyer/matches'
      path: '/matches'
      fullPath: '/buyer/matches'
      preLoaderRoute: typeof dashboardBuyerMatchesRouteImport
      parentRoute: typeof dashboardBuyerRouteRoute
    }
    '/(dashboard)/buyer/introductions': {
      id: '/(dashboard)/buyer/introductions'
      path: '/introductions'
      fullPath: '/buyer/introductions'
      preLoaderRoute: typeof dashboardBuyerIntroductionsRouteImport
      parentRoute: typeof dashboardBuyerRouteRoute
    }
    '/(dashboard)/agent/introductions': {
      id: '/(dashboard)/agent/introductions'
      path: '/introductions'
      fullPath: '/agent/introductions'
      preLoaderRoute: typeof dashboardAgentIntroductionsRouteImport
      parentRoute: typeof dashboardAgentRouteRoute
    }
    '/signup/(steps)/seller': {
      id: '/signup/(steps)/seller'
      path: '/signup/seller'
      fullPath: '/signup/seller'
      preLoaderRoute: typeof SignupstepsSellerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/(steps)/buyer': {
      id: '/signup/(steps)/buyer'
      path: '/signup/buyer'
      fullPath: '/signup/buyer'
      preLoaderRoute: typeof SignupstepsBuyerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/(steps)/agent': {
      id: '/signup/(steps)/agent'
      path: '/signup/agent'
      fullPath: '/signup/agent'
      preLoaderRoute: typeof SignupstepsAgentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest/static/$': {
      id: '/api/ingest/static/$'
      path: '/api/ingest/static/$'
      fullPath: '/api/ingest/static/$'
      preLoaderRoute: typeof ApiIngestStaticSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/(steps)/seller/(step-3)/preferences': {
      id: '/signup/(steps)/seller/(step-3)/preferences'
      path: '/preferences'
      fullPath: '/signup/seller/preferences'
      preLoaderRoute: typeof SignupstepsSellerstep3PreferencesRouteImport
      parentRoute: typeof SignupstepsSellerRouteRoute
    }
    '/signup/(steps)/seller/(step-2)/location': {
      id: '/signup/(steps)/seller/(step-2)/location'
      path: '/location'
      fullPath: '/signup/seller/location'
      preLoaderRoute: typeof SignupstepsSellerstep2LocationRouteImport
      parentRoute: typeof SignupstepsSellerRouteRoute
    }
    '/signup/(steps)/seller/(step-1)/home': {
      id: '/signup/(steps)/seller/(step-1)/home'
      path: '/home'
      fullPath: '/signup/seller/home'
      preLoaderRoute: typeof SignupstepsSellerstep1HomeRouteImport
      parentRoute: typeof SignupstepsSellerRouteRoute
    }
    '/signup/(steps)/buyer/(step-3)/preferences': {
      id: '/signup/(steps)/buyer/(step-3)/preferences'
      path: '/preferences'
      fullPath: '/signup/buyer/preferences'
      preLoaderRoute: typeof SignupstepsBuyerstep3PreferencesRouteImport
      parentRoute: typeof SignupstepsBuyerRouteRoute
    }
    '/signup/(steps)/buyer/(step-2)/location': {
      id: '/signup/(steps)/buyer/(step-2)/location'
      path: '/location'
      fullPath: '/signup/buyer/location'
      preLoaderRoute: typeof SignupstepsBuyerstep2LocationRouteImport
      parentRoute: typeof SignupstepsBuyerRouteRoute
    }
    '/signup/(steps)/buyer/(step-1)/home': {
      id: '/signup/(steps)/buyer/(step-1)/home'
      path: '/home'
      fullPath: '/signup/buyer/home'
      preLoaderRoute: typeof SignupstepsBuyerstep1HomeRouteImport
      parentRoute: typeof SignupstepsBuyerRouteRoute
    }
    '/signup/(steps)/agent/(step-5)/peace-pact': {
      id: '/signup/(steps)/agent/(step-5)/peace-pact'
      path: '/peace-pact'
      fullPath: '/signup/agent/peace-pact'
      preLoaderRoute: typeof SignupstepsAgentstep5PeacePactRouteImport
      parentRoute: typeof SignupstepsAgentRouteRoute
    }
    '/signup/(steps)/agent/(step-4)/compliance': {
      id: '/signup/(steps)/agent/(step-4)/compliance'
      path: '/compliance'
      fullPath: '/signup/agent/compliance'
      preLoaderRoute: typeof SignupstepsAgentstep4ComplianceRouteImport
      parentRoute: typeof SignupstepsAgentRouteRoute
    }
    '/signup/(steps)/agent/(step-3)/preferences': {
      id: '/signup/(steps)/agent/(step-3)/preferences'
      path: '/preferences'
      fullPath: '/signup/agent/preferences'
      preLoaderRoute: typeof SignupstepsAgentstep3PreferencesRouteImport
      parentRoute: typeof SignupstepsAgentRouteRoute
    }
    '/signup/(steps)/agent/(step-2)/market': {
      id: '/signup/(steps)/agent/(step-2)/market'
      path: '/market'
      fullPath: '/signup/agent/market'
      preLoaderRoute: typeof SignupstepsAgentstep2MarketRouteImport
      parentRoute: typeof SignupstepsAgentRouteRoute
    }
    '/signup/(steps)/agent/(step-1)/identity': {
      id: '/signup/(steps)/agent/(step-1)/identity'
      path: '/identity'
      fullPath: '/signup/agent/identity'
      preLoaderRoute: typeof SignupstepsAgentstep1IdentityRouteImport
      parentRoute: typeof SignupstepsAgentRouteRoute
    }
  }
}

interface dashboardAgentRouteRouteChildren {
  dashboardAgentIntroductionsRoute: typeof dashboardAgentIntroductionsRoute
}

const dashboardAgentRouteRouteChildren: dashboardAgentRouteRouteChildren = {
  dashboardAgentIntroductionsRoute: dashboardAgentIntroductionsRoute,
}

const dashboardAgentRouteRouteWithChildren =
  dashboardAgentRouteRoute._addFileChildren(dashboardAgentRouteRouteChildren)

interface dashboardBuyerRouteRouteChildren {
  dashboardBuyerIntroductionsRoute: typeof dashboardBuyerIntroductionsRoute
  dashboardBuyerMatchesRoute: typeof dashboardBuyerMatchesRoute
  dashboardBuyerPracticeNegotiatingRoute: typeof dashboardBuyerPracticeNegotiatingRoute
  dashboardBuyerSearchPreferencesRoute: typeof dashboardBuyerSearchPreferencesRoute
}

const dashboardBuyerRouteRouteChildren: dashboardBuyerRouteRouteChildren = {
  dashboardBuyerIntroductionsRoute: dashboardBuyerIntroductionsRoute,
  dashboardBuyerMatchesRoute: dashboardBuyerMatchesRoute,
  dashboardBuyerPracticeNegotiatingRoute:
    dashboardBuyerPracticeNegotiatingRoute,
  dashboardBuyerSearchPreferencesRoute: dashboardBuyerSearchPreferencesRoute,
}

const dashboardBuyerRouteRouteWithChildren =
  dashboardBuyerRouteRoute._addFileChildren(dashboardBuyerRouteRouteChildren)

interface dashboardSellerRouteRouteChildren {
  dashboardSellerIntroductionsRoute: typeof dashboardSellerIntroductionsRoute
  dashboardSellerMatchesRoute: typeof dashboardSellerMatchesRoute
  dashboardSellerPracticeNegotiatingRoute: typeof dashboardSellerPracticeNegotiatingRoute
  dashboardSellerSearchPreferencesRoute: typeof dashboardSellerSearchPreferencesRoute
}

const dashboardSellerRouteRouteChildren: dashboardSellerRouteRouteChildren = {
  dashboardSellerIntroductionsRoute: dashboardSellerIntroductionsRoute,
  dashboardSellerMatchesRoute: dashboardSellerMatchesRoute,
  dashboardSellerPracticeNegotiatingRoute:
    dashboardSellerPracticeNegotiatingRoute,
  dashboardSellerSearchPreferencesRoute: dashboardSellerSearchPreferencesRoute,
}

const dashboardSellerRouteRouteWithChildren =
  dashboardSellerRouteRoute._addFileChildren(dashboardSellerRouteRouteChildren)

interface SignupstepsAgentRouteRouteChildren {
  SignupstepsAgentstep1IdentityRoute: typeof SignupstepsAgentstep1IdentityRoute
  SignupstepsAgentstep2MarketRoute: typeof SignupstepsAgentstep2MarketRoute
  SignupstepsAgentstep3PreferencesRoute: typeof SignupstepsAgentstep3PreferencesRoute
  SignupstepsAgentstep4ComplianceRoute: typeof SignupstepsAgentstep4ComplianceRoute
  SignupstepsAgentstep5PeacePactRoute: typeof SignupstepsAgentstep5PeacePactRoute
}

const SignupstepsAgentRouteRouteChildren: SignupstepsAgentRouteRouteChildren = {
  SignupstepsAgentstep1IdentityRoute: SignupstepsAgentstep1IdentityRoute,
  SignupstepsAgentstep2MarketRoute: SignupstepsAgentstep2MarketRoute,
  SignupstepsAgentstep3PreferencesRoute: SignupstepsAgentstep3PreferencesRoute,
  SignupstepsAgentstep4ComplianceRoute: SignupstepsAgentstep4ComplianceRoute,
  SignupstepsAgentstep5PeacePactRoute: SignupstepsAgentstep5PeacePactRoute,
}

const SignupstepsAgentRouteRouteWithChildren =
  SignupstepsAgentRouteRoute._addFileChildren(
    SignupstepsAgentRouteRouteChildren,
  )

interface SignupstepsBuyerRouteRouteChildren {
  SignupstepsBuyerstep1HomeRoute: typeof SignupstepsBuyerstep1HomeRoute
  SignupstepsBuyerstep2LocationRoute: typeof SignupstepsBuyerstep2LocationRoute
  SignupstepsBuyerstep3PreferencesRoute: typeof SignupstepsBuyerstep3PreferencesRoute
}

const SignupstepsBuyerRouteRouteChildren: SignupstepsBuyerRouteRouteChildren = {
  SignupstepsBuyerstep1HomeRoute: SignupstepsBuyerstep1HomeRoute,
  SignupstepsBuyerstep2LocationRoute: SignupstepsBuyerstep2LocationRoute,
  SignupstepsBuyerstep3PreferencesRoute: SignupstepsBuyerstep3PreferencesRoute,
}

const SignupstepsBuyerRouteRouteWithChildren =
  SignupstepsBuyerRouteRoute._addFileChildren(
    SignupstepsBuyerRouteRouteChildren,
  )

interface SignupstepsSellerRouteRouteChildren {
  SignupstepsSellerstep1HomeRoute: typeof SignupstepsSellerstep1HomeRoute
  SignupstepsSellerstep2LocationRoute: typeof SignupstepsSellerstep2LocationRoute
  SignupstepsSellerstep3PreferencesRoute: typeof SignupstepsSellerstep3PreferencesRoute
}

const SignupstepsSellerRouteRouteChildren: SignupstepsSellerRouteRouteChildren =
  {
    SignupstepsSellerstep1HomeRoute: SignupstepsSellerstep1HomeRoute,
    SignupstepsSellerstep2LocationRoute: SignupstepsSellerstep2LocationRoute,
    SignupstepsSellerstep3PreferencesRoute:
      SignupstepsSellerstep3PreferencesRoute,
  }

const SignupstepsSellerRouteRouteWithChildren =
  SignupstepsSellerRouteRoute._addFileChildren(
    SignupstepsSellerRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  dashboardAgentRouteRoute: dashboardAgentRouteRouteWithChildren,
  dashboardBuyerRouteRoute: dashboardBuyerRouteRouteWithChildren,
  dashboardSellerRouteRoute: dashboardSellerRouteRouteWithChildren,
  AuthBetaRoute: AuthBetaRoute,
  AuthCompleteRoute: AuthCompleteRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  SignupstepsAgentRouteRoute: SignupstepsAgentRouteRouteWithChildren,
  SignupstepsBuyerRouteRoute: SignupstepsBuyerRouteRouteWithChildren,
  SignupstepsSellerRouteRoute: SignupstepsSellerRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiIngestSplatRoute: ApiIngestSplatRoute,
  SignupPreviewAgentRoute: SignupPreviewAgentRoute,
  SignupPreviewBuyerRoute: SignupPreviewBuyerRoute,
  SignupPreviewSellerRoute: SignupPreviewSellerRoute,
  ApiIngestStaticSplatRoute: ApiIngestStaticSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
